### ISSUE TITLE
No data recieved or transmitted

### ISSUE THREAD

**Issue by banym** [ahupowerdns/galmon#55]
./ubxtool --wait --port /dev/ttyACM0 --station 1 --gps --stdout | ./navparse 127.0.0.1:10000 html null

leads to following output:

Unknown type 10
Unknown type 10
Unknown type 10
Unknown type 10
Unknown type 10

**Comment by mahtin** [comment]
It seems like you are not hearing any satellites. Try to add some additional constellations with `--galileo --beidou` command lines (or simply move the antenna to get a better view).

As for the `Unknown type 10` message, that's from `navparse` because presently `nmm.set_type(NavMonMessage::DebuggingType);` isn't coded into `navparse` or `navdump`.

**Comment by banym** [comment]
I am using an odroid arm64 board running ubuntu 18.04 and a navilock 8012U with latest firmware. Mostly I am interested in monitoring Galileo satellites, now with --gps --galileo --beidou I see multiple GPS and Beidou but no Galileo satellites. Have you got a hint where to start?
